{{ if .Values.cleanup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ytdl-k8s.fullname" . }}-cleanup
  labels:
    {{- include "ytdl-k8s.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cleanup.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleanup
              image: "{{ .Values.cleanup.image.repository }}:{{ .Values.cleanup.image.tag }}"
              imagePullPolicy: "{{ .Values.cleanup.image.pullPolicy }}"
              command:
                # Remove empty dirs
                - /bin/sh
                - -c
                - 'find /youtube-dl -type d -empty -print -exec rmdir \{\} \;'
              volumeMounts:
                - name: downloads
                  mountPath: /youtube-dl
          restartPolicy: OnFailure

          volumes:
            - name: downloads
              {{- toYaml .Values.storage.downloads.volume | nindent 14 }}
{{ end }}