apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ytdl-k8s.fullname" . }}-config
  labels:
    {{- include "ytdl-k8s.labels" . | nindent 4 }}
data:
{{- (.Files.Glob "scripts/*.sh").AsConfig | nindent 4 }}
    config.yml: |
        ydl_server:   # ytdl-k8s specific settings
            port: 8080      # Port ytdl-k8s should listen on
            host: 0.0.0.0   # IP ytdl-k8s should bind to
            debug: {{ dig "server" "debug" "False" .Values.ytdl }}    # Enable/Disable debug mode
            metadata_db_path: '/youtube-dl/.ydl-metadata.db' # Path to metadata DB
            output_playlist: '/youtube-dl/{{ .Values.ytdl.playlist_template }}'
            max_log_entries: 100 # Maximum number of job log history to keep
            forwarded_allow_ips: None # uvicorn Comma seperated list of IPs to trust with proxy headers.
            proxy_headers: True # uvicorn flag Enable/Disable X-Forwarded-Proto, X-Forwarded-For, X-Forwarded-Port to populate remote address info.
            default_format: video/best # Default format selection
            download_workers_count: 2 # Number of download worker threads

        ydl_options:  # youtube-dl options
            output: '/youtube-dl/{{ .Values.ytdl.output_template }}'
            cache-dir: '/youtube-dl/.cache' # youtube-dl cache directory
            ignore-errors: True # instruct youtube-dl to skip errors
            age-limit: 6 # minimal age requirement / parental control setting
            {{- range $key, $value := .Values.ytdl.options }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
